language: python
cache: pip

matrix:
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
    - python: pypy
    - python: pypy3

before_install:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then pip install codecov; fi

# command to install dependencies
install:
  - make install-dev

# command to run tests
script:
  - make lint
  - make test

# command to upload coverage
after_success:
- if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then codecov; fi
